"""E13 pack salud nutricion

Revision ID: 8005879005ed
Revises: 89ecc29f544d
Create Date: 2026-06-23 17:30:06.560977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8005879005ed'
down_revision: Union[str, None] = '89ecc29f544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha_clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('ocupacion', sa.String(length=200), nullable=True),
    sa.Column('horario_trabajo', sa.String(length=200), nullable=True),
    sa.Column('fum', sa.Date(), nullable=True),
    sa.Column('horario_comidas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recordatorio_24h', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frecuencia_consumo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actividad_fisica', sa.Text(), nullable=True),
    sa.Column('enfermedades', sa.Text(), nullable=True),
    sa.Column('operaciones', sa.Text(), nullable=True),
    sa.Column('medicacion', sa.Text(), nullable=True),
    sa.Column('antecedentes_familiares', sa.Text(), nullable=True),
    sa.Column('consume_alcohol_drogas', sa.String(length=200), nullable=True),
    sa.Column('fuma', sa.String(length=120), nullable=True),
    sa.Column('sintomas_recurrentes', sa.Text(), nullable=True),
    sa.Column('evacuacion', sa.String(length=200), nullable=True),
    sa.Column('sueno', sa.String(length=200), nullable=True),
    sa.Column('alimentos_no_consume', sa.Text(), nullable=True),
    sa.Column('alimentos_no_tolera', sa.Text(), nullable=True),
    sa.Column('alimentos_gustan', sa.Text(), nullable=True),
    sa.Column('nutri_anterior', sa.Text(), nullable=True),
    sa.Column('obra_social', sa.String(length=120), nullable=True),
    sa.Column('plan_obra_social', sa.String(length=120), nullable=True),
    sa.Column('nro_afiliado', sa.String(length=60), nullable=True),
    sa.Column('datos_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_ficha_clinica_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_ficha_clinica_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ficha_clinica')),
    sa.UniqueConstraint('empresa_id', 'cliente_id', name='uq_ficha_empresa_cliente')
    )
    op.create_index(op.f('ix_ficha_clinica_empresa_id'), 'ficha_clinica', ['empresa_id'], unique=False)
    op.create_index('ix_ficha_empresa_cliente', 'ficha_clinica', ['empresa_id', 'cliente_id'], unique=False)
    op.create_table('entrada_clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('como_se_sintio', sa.Text(), nullable=True),
    sa.Column('noto_diferencia', sa.Text(), nullable=True),
    sa.Column('apetito', sa.Text(), nullable=True),
    sa.Column('entrenamiento', sa.Text(), nullable=True),
    sa.Column('descanso', sa.Text(), nullable=True),
    sa.Column('estres', sa.Text(), nullable=True),
    sa.Column('resumen_antropometria', sa.Text(), nullable=True),
    sa.Column('prescripcion', sa.Text(), nullable=True),
    sa.Column('proximo_turno', sa.Date(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_entrada_clinica_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_entrada_clinica_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], name=op.f('fk_entrada_clinica_turno_id_turno')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrada_clinica'))
    )
    op.create_index(op.f('ix_entrada_clinica_empresa_id'), 'entrada_clinica', ['empresa_id'], unique=False)
    op.create_index('ix_entrada_empresa_cliente_fecha', 'entrada_clinica', ['empresa_id', 'cliente_id', 'fecha'], unique=False)
    op.create_table('medicion_antropometrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('evaluador', sa.String(length=120), nullable=True),
    sa.Column('origen', sa.String(length=40), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('talla_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('imc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('talla_sentado_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('envergadura_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pl_triceps', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_subescapular', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_biceps', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_cresta_iliaca', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_supraespinal', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_abdominal', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_muslo', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pl_pierna', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sumatoria_pliegues', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('per_cintura', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('per_cadera', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('per_brazo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('per_muslo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('per_pierna', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('masa_grasa_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('masa_grasa_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('masa_muscular_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('masa_osea_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('datos_isak', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_medicion_antropometrica_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_medicion_antropometrica_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrada_clinica.id'], name=op.f('fk_medicion_antropometrica_entrada_id_entrada_clinica')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicion_antropometrica'))
    )
    op.create_index(op.f('ix_medicion_antropometrica_empresa_id'), 'medicion_antropometrica', ['empresa_id'], unique=False)
    op.create_index('ix_medicion_empresa_cliente_fecha', 'medicion_antropometrica', ['empresa_id', 'cliente_id', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medicion_empresa_cliente_fecha', table_name='medicion_antropometrica')
    op.drop_index(op.f('ix_medicion_antropometrica_empresa_id'), table_name='medicion_antropometrica')
    op.drop_table('medicion_antropometrica')
    op.drop_index('ix_entrada_empresa_cliente_fecha', table_name='entrada_clinica')
    op.drop_index(op.f('ix_entrada_clinica_empresa_id'), table_name='entrada_clinica')
    op.drop_table('entrada_clinica')
    op.drop_index('ix_ficha_empresa_cliente', table_name='ficha_clinica')
    op.drop_index(op.f('ix_ficha_clinica_empresa_id'), table_name='ficha_clinica')
    op.drop_table('ficha_clinica')
    # ### end Alembic commands ###