"""E10 items adicionales de turno

Revision ID: 62f8e80b4e0e
Revises: 8005879005ed
Create Date: 2026-06-23 23:12:09.564816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62f8e80b4e0e'
down_revision: Union[str, None] = '8005879005ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=160), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_item_turno_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], name=op.f('fk_item_turno_turno_id_turno')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_turno'))
    )
    op.create_index(op.f('ix_item_turno_empresa_id'), 'item_turno', ['empresa_id'], unique=False)
    op.create_index('ix_item_turno_empresa_turno', 'item_turno', ['empresa_id', 'turno_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_turno_empresa_turno', table_name='item_turno')
    op.drop_index(op.f('ix_item_turno_empresa_id'), table_name='item_turno')
    op.drop_table('item_turno')
    # ### end Alembic commands ###