"""E10 descuento en turno

Revision ID: ec80f77e95fc
Revises: e847d2c62fe5
Create Date: 2026-06-24 18:57:07.555385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec80f77e95fc'
down_revision: Union[str, None] = 'e847d2c62fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turno', sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turno', 'descuento_pct')
    # ### end Alembic commands ###