"""agrega paso_turno_min a servicio

Revision ID: c8c545bbada8
Revises: d3d21b3f8886
Create Date: 2026-06-14 00:22:34.089022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8c545bbada8'
down_revision: Union[str, None] = 'd3d21b3f8886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('paso_turno_min', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'paso_turno_min')
    # ### end Alembic commands ###