"""Tope de sucursales por empresa.

El gemelo de `limite_recursos`, que ya existía: pisa el tope que trae el plan
(app/core/planes.py). Vacío = manda la grilla.

Existe por dos razones prácticas: hacerle un cupo especial a un cliente sin
inventar un plan nuevo, y poder dejar tranquilo a alguien que ya tenía más
cargado que lo que su plan admite el día que se enciende el enforcement

Revision ID: ebc752b65ee7
Revises: aad671f768b9
Create Date: 2026-08-28 22:59:42.160588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebc752b65ee7'
down_revision: Union[str, None] = 'aad671f768b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('limite_sucursales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'limite_sucursales')
    # ### end Alembic commands ###