"""agrega grupo_agenda a servicio

Revision ID: e1801ea45cc8
Revises: c8c545bbada8
Create Date: 2026-06-15 16:49:12.627546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1801ea45cc8'
down_revision: Union[str, None] = 'c8c545bbada8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('grupo_agenda', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'grupo_agenda')
    # ### end Alembic commands ###