"""E1 nucleo inicial

Revision ID: d3d21b3f8886
Revises: 
Create Date: 2026-06-12 15:09:43.891243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd3d21b3f8886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('preset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubro')),
    sa.UniqueConstraint('codigo', name=op.f('uq_rubro_codigo'))
    )
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hash_clave', sa.String(length=300), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_admin')),
    sa.UniqueConstraint('email', name=op.f('uq_super_admin_email'))
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('config_pack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wa_credenciales', postgresql.BYTEA(), nullable=True),
    sa.Column('email_credenciales', postgresql.BYTEA(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], name=op.f('fk_empresa_rubro_id_rubro')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('slug', name=op.f('uq_empresa_slug'))
    )
    op.create_table('categoria_financiera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipo_movimiento'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_categoria_financiera_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria_financiera'))
    )
    op.create_index(op.f('ix_categoria_financiera_empresa_id'), 'categoria_financiera', ['empresa_id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('canal_adquisicion', sa.String(length=60), nullable=True),
    sa.Column('campos_rubro', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etiquetas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_cliente_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente'))
    )
    op.create_index('ix_cliente_empresa_apellido_nombre', 'cliente', ['empresa_id', 'apellido', 'nombre'], unique=False)
    op.create_index('ix_cliente_empresa_dni', 'cliente', ['empresa_id', 'dni'], unique=False)
    op.create_index(op.f('ix_cliente_empresa_id'), 'cliente', ['empresa_id'], unique=False)
    op.create_index('ix_cliente_empresa_telefono', 'cliente', ['empresa_id', 'telefono'], unique=False)
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_especialidad_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_especialidad'))
    )
    op.create_index(op.f('ix_especialidad_empresa_id'), 'especialidad', ['empresa_id'], unique=False)
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('comision_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_metodo_pago_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metodo_pago'))
    )
    op.create_index(op.f('ix_metodo_pago_empresa_id'), 'metodo_pago', ['empresa_id'], unique=False)
    op.create_table('plantilla_mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('whatsapp', 'email', name='canal_mensaje'), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('aprobada_meta', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_plantilla_mensaje_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plantilla_mensaje'))
    )
    op.create_index(op.f('ix_plantilla_mensaje_empresa_id'), 'plantilla_mensaje', ['empresa_id'], unique=False)
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('buffer_min', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_servicio_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicio'))
    )
    op.create_index('ix_servicio_empresa_activo', 'servicio', ['empresa_id', 'activo'], unique=False)
    op.create_index(op.f('ix_servicio_empresa_id'), 'servicio', ['empresa_id'], unique=False)
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_sucursal_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sucursal'))
    )
    op.create_index(op.f('ix_sucursal_empresa_id'), 'sucursal', ['empresa_id'], unique=False)
    op.create_table('deuda_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldada', sa.Boolean(), nullable=False),
    sa.Column('ref_tabla', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_deuda_cliente_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_deuda_cliente_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deuda_cliente'))
    )
    op.create_index(op.f('ix_deuda_cliente_empresa_id'), 'deuda_cliente', ['empresa_id'], unique=False)
    op.create_table('historial_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('ref_tabla', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_historial_cliente_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_historial_cliente_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_cliente'))
    )
    op.create_index(op.f('ix_historial_cliente_empresa_id'), 'historial_cliente', ['empresa_id'], unique=False)
    op.create_index('ix_historial_empresa_cliente_fecha', 'historial_cliente', ['empresa_id', 'cliente_id', 'fecha'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hash_clave', sa.String(length=300), nullable=False),
    sa.Column('rol', sa.Enum('dueno', 'admin', 'recepcion', 'profesional', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_usuario_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_usuario_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('empresa_id', 'email', name=op.f('uq_usuario_empresa_id'))
    )
    op.create_index(op.f('ix_usuario_empresa_id'), 'usuario', ['empresa_id'], unique=False)
    op.create_table('adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('entrada_clinica_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_adjunto_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_adjunto_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['subido_por'], ['usuario.id'], name=op.f('fk_adjunto_subido_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjunto'))
    )
    op.create_index(op.f('ix_adjunto_empresa_id'), 'adjunto', ['empresa_id'], unique=False)
    op.create_table('caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('abierta', 'cerrada', name='estado_caja'), nullable=False),
    sa.Column('abierta_por', sa.Integer(), nullable=True),
    sa.Column('cerrada_por', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abierta_por'], ['usuario.id'], name=op.f('fk_caja_abierta_por_usuario')),
    sa.ForeignKeyConstraint(['cerrada_por'], ['usuario.id'], name=op.f('fk_caja_cerrada_por_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_caja_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_caja_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caja'))
    )
    op.create_index(op.f('ix_caja_empresa_id'), 'caja', ['empresa_id'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('tabla', sa.String(length=60), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_log_auditoria_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_log_auditoria_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_auditoria'))
    )
    op.create_index(op.f('ix_log_auditoria_empresa_id'), 'log_auditoria', ['empresa_id'], unique=False)
    op.create_index('ix_log_empresa_fecha', 'log_auditoria', ['empresa_id', 'fecha'], unique=False)
    op.create_index('ix_log_tabla_registro', 'log_auditoria', ['tabla', 'registro_id'], unique=False)
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('persona', 'box', 'equipo', name='tipo_recurso'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_recurso_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_recurso_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_recurso_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurso'))
    )
    op.create_index(op.f('ix_recurso_empresa_id'), 'recurso', ['empresa_id'], unique=False)
    op.create_index('ix_recurso_empresa_tipo', 'recurso', ['empresa_id', 'tipo'], unique=False)
    op.create_table('comision_profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.Enum('porcentaje', 'canon_consulta', 'alquiler', name='modalidad_comision'), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_comision_profesional_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_comision_profesional_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comision_profesional'))
    )
    op.create_index(op.f('ix_comision_profesional_empresa_id'), 'comision_profesional', ['empresa_id'], unique=False)
    op.create_table('excepcion_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('feriado', 'licencia', 'vacaciones', 'bloqueo', name='tipo_excepcion'), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_excepcion_agenda_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_excepcion_agenda_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excepcion_agenda'))
    )
    op.create_index(op.f('ix_excepcion_agenda_empresa_id'), 'excepcion_agenda', ['empresa_id'], unique=False)
    op.create_table('horario_recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_desde', sa.Time(), nullable=False),
    sa.Column('hora_hasta', sa.Time(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_horario_recurso_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_horario_recurso_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horario_recurso'))
    )
    op.create_index('ix_horario_empresa_recurso_dia', 'horario_recurso', ['empresa_id', 'recurso_id', 'dia_semana'], unique=False)
    op.create_index(op.f('ix_horario_recurso_empresa_id'), 'horario_recurso', ['empresa_id'], unique=False)
    op.create_table('lista_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('rango_preferido', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_lista_espera_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_lista_espera_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_lista_espera_recurso_id_recurso')),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name=op.f('fk_lista_espera_servicio_id_servicio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lista_espera'))
    )
    op.create_index(op.f('ix_lista_espera_empresa_id'), 'lista_espera', ['empresa_id'], unique=False)
    op.create_table('movimiento_financiero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipo_movimiento'), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['caja.id'], name=op.f('fk_movimiento_financiero_caja_id_caja')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_financiera.id'], name=op.f('fk_movimiento_financiero_categoria_id_categoria_financiera')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_movimiento_financiero_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], name=op.f('fk_movimiento_financiero_metodo_pago_id_metodo_pago')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimiento_financiero_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_financiero'))
    )
    op.create_index('ix_movfin_empresa_fecha', 'movimiento_financiero', ['empresa_id', 'fecha'], unique=False)
    op.create_index('ix_movfin_empresa_tipo_categoria', 'movimiento_financiero', ['empresa_id', 'tipo', 'categoria_id'], unique=False)
    op.create_index(op.f('ix_movimiento_financiero_empresa_id'), 'movimiento_financiero', ['empresa_id'], unique=False)
    op.create_table('recurso_especialidad',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], name=op.f('fk_recurso_especialidad_especialidad_id_especialidad')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_recurso_especialidad_recurso_id_recurso')),
    sa.PrimaryKeyConstraint('recurso_id', 'especialidad_id', name=op.f('pk_recurso_especialidad'))
    )
    op.create_table('servicio_recurso',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_servicio_recurso_recurso_id_recurso')),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name=op.f('fk_servicio_recurso_servicio_id_servicio')),
    sa.PrimaryKeyConstraint('servicio_id', 'recurso_id', name=op.f('pk_servicio_recurso'))
    )
    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('paquete_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('simple', 'recurrente', 'serie', 'orden_llegada', 'orden_trabajo', name='tipo_turno'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'en_curso', 'finalizado', 'cancelado', 'ausente', name='estado_turno'), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posicion_cola', sa.Integer(), nullable=True),
    sa.Column('serie_grupo_id', sa.Integer(), nullable=True),
    sa.Column('es_sobreturno', sa.Boolean(), nullable=False),
    sa.Column('importe_previsto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=300), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_turno_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name=op.f('fk_turno_creado_por_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_turno_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], name=op.f('fk_turno_recurso_id_recurso')),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name=op.f('fk_turno_servicio_id_servicio')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_turno_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turno'))
    )
    op.create_index('ix_turno_empresa_cliente', 'turno', ['empresa_id', 'cliente_id'], unique=False)
    op.create_index('ix_turno_empresa_estado_inicio', 'turno', ['empresa_id', 'estado', 'fecha_inicio'], unique=False)
    op.create_index(op.f('ix_turno_empresa_id'), 'turno', ['empresa_id'], unique=False)
    op.create_index('ix_turno_empresa_recurso_inicio', 'turno', ['empresa_id', 'recurso_id', 'fecha_inicio'], unique=False)
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_calificacion_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_calificacion_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], name=op.f('fk_calificacion_turno_id_turno')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calificacion'))
    )
    op.create_index(op.f('ix_calificacion_empresa_id'), 'calificacion', ['empresa_id'], unique=False)
    op.create_table('mensaje',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('whatsapp', 'email', name='canal_mensaje'), nullable=False),
    sa.Column('direccion', sa.Enum('saliente', 'entrante', name='direccion_mensaje'), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'entregado', 'leido', 'fallido', name='estado_mensaje'), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_mensaje_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_mensaje_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantilla_mensaje.id'], name=op.f('fk_mensaje_plantilla_id_plantilla_mensaje')),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], name=op.f('fk_mensaje_turno_id_turno')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensaje'))
    )
    op.create_index('ix_mensaje_empresa_cliente', 'mensaje', ['empresa_id', 'cliente_id'], unique=False)
    op.create_index('ix_mensaje_empresa_fecha', 'mensaje', ['empresa_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_mensaje_empresa_id'), 'mensaje', ['empresa_id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comision_aplicada', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_pago_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_pago_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], name=op.f('fk_pago_metodo_pago_id_metodo_pago')),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento_financiero.id'], name=op.f('fk_pago_movimiento_id_movimiento_financiero')),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], name=op.f('fk_pago_turno_id_turno')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pago'))
    )
    op.create_index(op.f('ix_pago_empresa_id'), 'pago', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_empresa_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_mensaje_empresa_id'), table_name='mensaje')
    op.drop_index('ix_mensaje_empresa_fecha', table_name='mensaje')
    op.drop_index('ix_mensaje_empresa_cliente', table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_index(op.f('ix_calificacion_empresa_id'), table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index('ix_turno_empresa_recurso_inicio', table_name='turno')
    op.drop_index(op.f('ix_turno_empresa_id'), table_name='turno')
    op.drop_index('ix_turno_empresa_estado_inicio', table_name='turno')
    op.drop_index('ix_turno_empresa_cliente', table_name='turno')
    op.drop_table('turno')
    op.drop_table('servicio_recurso')
    op.drop_table('recurso_especialidad')
    op.drop_index(op.f('ix_movimiento_financiero_empresa_id'), table_name='movimiento_financiero')
    op.drop_index('ix_movfin_empresa_tipo_categoria', table_name='movimiento_financiero')
    op.drop_index('ix_movfin_empresa_fecha', table_name='movimiento_financiero')
    op.drop_table('movimiento_financiero')
    op.drop_index(op.f('ix_lista_espera_empresa_id'), table_name='lista_espera')
    op.drop_table('lista_espera')
    op.drop_index(op.f('ix_horario_recurso_empresa_id'), table_name='horario_recurso')
    op.drop_index('ix_horario_empresa_recurso_dia', table_name='horario_recurso')
    op.drop_table('horario_recurso')
    op.drop_index(op.f('ix_excepcion_agenda_empresa_id'), table_name='excepcion_agenda')
    op.drop_table('excepcion_agenda')
    op.drop_index(op.f('ix_comision_profesional_empresa_id'), table_name='comision_profesional')
    op.drop_table('comision_profesional')
    op.drop_index('ix_recurso_empresa_tipo', table_name='recurso')
    op.drop_index(op.f('ix_recurso_empresa_id'), table_name='recurso')
    op.drop_table('recurso')
    op.drop_index('ix_log_tabla_registro', table_name='log_auditoria')
    op.drop_index('ix_log_empresa_fecha', table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_empresa_id'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_caja_empresa_id'), table_name='caja')
    op.drop_table('caja')
    op.drop_index(op.f('ix_adjunto_empresa_id'), table_name='adjunto')
    op.drop_table('adjunto')
    op.drop_index(op.f('ix_usuario_empresa_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index('ix_historial_empresa_cliente_fecha', table_name='historial_cliente')
    op.drop_index(op.f('ix_historial_cliente_empresa_id'), table_name='historial_cliente')
    op.drop_table('historial_cliente')
    op.drop_index(op.f('ix_deuda_cliente_empresa_id'), table_name='deuda_cliente')
    op.drop_table('deuda_cliente')
    op.drop_index(op.f('ix_sucursal_empresa_id'), table_name='sucursal')
    op.drop_table('sucursal')
    op.drop_index(op.f('ix_servicio_empresa_id'), table_name='servicio')
    op.drop_index('ix_servicio_empresa_activo', table_name='servicio')
    op.drop_table('servicio')
    op.drop_index(op.f('ix_plantilla_mensaje_empresa_id'), table_name='plantilla_mensaje')
    op.drop_table('plantilla_mensaje')
    op.drop_index(op.f('ix_metodo_pago_empresa_id'), table_name='metodo_pago')
    op.drop_table('metodo_pago')
    op.drop_index(op.f('ix_especialidad_empresa_id'), table_name='especialidad')
    op.drop_table('especialidad')
    op.drop_index('ix_cliente_empresa_telefono', table_name='cliente')
    op.drop_index(op.f('ix_cliente_empresa_id'), table_name='cliente')
    op.drop_index('ix_cliente_empresa_dni', table_name='cliente')
    op.drop_index('ix_cliente_empresa_apellido_nombre', table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_categoria_financiera_empresa_id'), table_name='categoria_financiera')
    op.drop_table('categoria_financiera')
    op.drop_table('empresa')
    op.drop_table('super_admin')
    op.drop_table('rubro')
    # ### end Alembic commands ###