"""E10 servicio agendable

Revision ID: e847d2c62fe5
Revises: 62f8e80b4e0e
Create Date: 2026-06-24 04:41:15.106689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e847d2c62fe5'
down_revision: Union[str, None] = '62f8e80b4e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('agendable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'agendable')
    # ### end Alembic commands ###