"""Verificación de email y marca de registro público.

Las cuentas que YA existen se marcan como verificadas en el backfill: las dio
de alta el super-admin a mano, o sea que Leandro conoce a esas personas. Sin
ese UPDATE, todos los negocios que están andando hoy quedarían con su vidriera
pública apagada de un día para el otro — el candado anti-spam se les aplicaría
a quienes nunca fueron el problema

Revision ID: f22c3d3bb82a
Revises: ebc752b65ee7
Create Date: 2026-08-29 13:42:55.161940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f22c3d3bb82a'
down_revision: Union[str, None] = 'ebc752b65ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('de_registro_publico', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuario', sa.Column('email_verificado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuario', sa.Column('verif_token_hash', sa.String(length=128), nullable=True))
    op.add_column('usuario', sa.Column('verif_token_expira', sa.DateTime(timezone=True), nullable=True))

    # Backfill: lo que ya existe queda verificado. Ver el docstring.
    op.execute("UPDATE usuario SET email_verificado = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'verif_token_expira')
    op.drop_column('usuario', 'verif_token_hash')
    op.drop_column('usuario', 'email_verificado')
    op.drop_column('empresa', 'de_registro_publico')
    # ### end Alembic commands ###