"""Cobro de la suscripción por Mercado Pago y avisos de transferencia.

Dos cosas distintas y complementarias:

· `pago_suscripcion.mp_payment_id` con índice único parcial: es la
  idempotencia del webhook de suscripciones. Mercado Pago reintenta la misma
  notificación varias veces, y sin esto cada reintento renovaba otros 30 días.
  El único parcial deja convivir todas las cuotas cargadas a mano (que no
  tienen id de MP) sin chocar entre ellas.

· `aviso_pago`: el negocio avisa "ya te transferí". NO es una cuota todavía —
  una transferencia tarda en verse en la cuenta, y anotarla en el momento en
  que alguien dice que pagó convierte el MRR en un número de buena fe. El
  aviso le da al dueño su "en 24 h lo ves reflejado" y a Leandro una bandeja
  con lo que tiene que confirmar contra el banco

Revision ID: aad671f768b9
Revises: f86b7eda5fb0
Create Date: 2026-08-25 02:27:04.159919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aad671f768b9'
down_revision: Union[str, None] = 'f86b7eda5fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=40), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('avisado_por', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resuelto_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resuelto_por', sa.String(length=160), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_aviso_pago_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['pago_id'], ['pago_suscripcion.id'], name=op.f('fk_aviso_pago_pago_id_pago_suscripcion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aviso_pago'))
    )
    op.create_index(op.f('ix_aviso_pago_empresa_id'), 'aviso_pago', ['empresa_id'], unique=False)
    op.create_index('ix_aviso_pago_pendiente', 'aviso_pago', ['creado_en'], unique=False, postgresql_where=sa.text('resuelto = false'))
    op.add_column('pago_suscripcion', sa.Column('mp_payment_id', sa.String(length=40), nullable=True))
    op.create_index('uq_pago_suscripcion_mp', 'pago_suscripcion', ['mp_payment_id'], unique=True, postgresql_where=sa.text('mp_payment_id is not null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pago_suscripcion_mp', table_name='pago_suscripcion', postgresql_where=sa.text('mp_payment_id is not null'))
    op.drop_column('pago_suscripcion', 'mp_payment_id')
    op.drop_index('ix_aviso_pago_pendiente', table_name='aviso_pago', postgresql_where=sa.text('resuelto = false'))
    op.drop_index(op.f('ix_aviso_pago_empresa_id'), table_name='aviso_pago')
    op.drop_table('aviso_pago')
    # ### end Alembic commands ###