"""E11 membresias - plan_abono y membresia

Revision ID: a268ad0f87ff
Revises: e1801ea45cc8
Create Date: 2026-06-18 22:02:09.652658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a268ad0f87ff'
down_revision: Union[str, None] = 'e1801ea45cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ilimitado', sa.Boolean(), nullable=False),
    sa.Column('cantidad_cupos', sa.Integer(), nullable=True),
    sa.Column('servicios_cubiertos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_plan_abono_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_abono'))
    )
    op.create_index('ix_plan_abono_empresa_activo', 'plan_abono', ['empresa_id', 'activo'], unique=False)
    op.create_index(op.f('ix_plan_abono_empresa_id'), 'plan_abono', ['empresa_id'], unique=False)
    op.create_table('membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'SUSPENDIDA', 'VENCIDA', 'PENDIENTE_PAGO', name='estado_membresia'), nullable=False),
    sa.Column('cupos_usados', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_membresia_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_membresia_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_abono.id'], name=op.f('fk_membresia_plan_id_plan_abono')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membresia'))
    )
    op.create_index('ix_membresia_empresa_cliente', 'membresia', ['empresa_id', 'cliente_id'], unique=False)
    op.create_index(op.f('ix_membresia_empresa_id'), 'membresia', ['empresa_id'], unique=False)
    op.create_index('ix_membresia_vigencia', 'membresia', ['empresa_id', 'fecha_hasta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_membresia_vigencia', table_name='membresia')
    op.drop_index(op.f('ix_membresia_empresa_id'), table_name='membresia')
    op.drop_index('ix_membresia_empresa_cliente', table_name='membresia')
    op.drop_table('membresia')
    op.drop_index(op.f('ix_plan_abono_empresa_id'), table_name='plan_abono')
    op.drop_index('ix_plan_abono_empresa_activo', table_name='plan_abono')
    op.drop_table('plan_abono')
    # ### end Alembic commands ###