"""turno cubierto_por_abono

Revision ID: 89ecc29f544d
Revises: a268ad0f87ff
Create Date: 2026-06-19 02:22:45.338699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89ecc29f544d'
down_revision: Union[str, None] = 'a268ad0f87ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('turno', sa.Column('cubierto_por_abono', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turno', 'cubierto_por_abono')
    # ### end Alembic commands ###