"""cobrado en turno

Revision ID: 90834f6bc23f
Revises: ec80f77e95fc
Create Date: 2026-06-26 13:31:55.576556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90834f6bc23f'
down_revision: Union[str, None] = 'ec80f77e95fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turno', sa.Column('cobrado', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turno', 'cobrado')
    # ### end Alembic commands ###